name: generate languages metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          filename: plugin.languages.svg
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          committer_branch: output
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          extras_css: |
            :root{--bg:transparent}svg{background:transparent!important}
