name: generate languages metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: plugin.languages.svg
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage
          extras_css: |
            :root{--bg:transparent}svg{background:transparent!important}

      - name: organize into subfolder
        shell: bash
        run: |
          mkdir -p output-files/metrics
          mv plugin.*.svg output-files/metrics/

      - name: push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          publish_dir: ./output-files
          publish_branch: output
          keep_files: true
