name: generate lowlighter metrics

on:
  schedule:
    - cron: "30 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: lowlighter/metrics@latest
        with:
          filename: plugin.starlists.languages.svg
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          committer_branch: output
          base: ""
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_limit_repositories: 0
          plugin_starlists_limit_languages: 8
          extras_css: |
            :root{--bg:transparent}svg{background:transparent!important}

      - uses: lowlighter/metrics@latest
        with:
          filename: plugin.topics.icons.svg
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          committer_branch: output
          base: ""
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 15
          extras_css: |
            :root{--bg:transparent}svg{background:transparent!important}

      - uses: lowlighter/metrics@latest
        with:
          filename: plugin.achievements.svg
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          committer_branch: output
          base: header
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          extras_css: |
            :root{--bg:transparent}svg{background:transparent!important}

      - uses: lowlighter/metrics@latest
        with:
          filename: plugin.habits.facts.svg
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          committer_branch: output
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_days: 30
          plugin_habits_charts: no
          config_timezone: Asia/Kolkata
          extras_css: |
            :root{--bg:transparent}svg{background:transparent!important}

      - uses: lowlighter/metrics@latest
        with:
          filename: plugin.habits.charts.svg
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          committer_branch: output
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          config_timezone: Asia/Kolkata
          extras_css: |
            :root{--bg:transparent}svg{background:transparent!important}

      - uses: lowlighter/metrics@latest
        with:
          filename: plugin.introduction.svg
          token: ${{ secrets.SECRET_GITHUB_TOKEN }}
          committer_branch: output
          base: header, activity, community, repositories, metadata
          base_indepth: true
          base_hireable: true
          repositories_forks: true
          plugin_lines: yes
          plugin_lines_sections: base
          config_timezone: Asia/Kolkata
          config_twemoji: true
          extras_css: |
            :root{--bg:transparent}svg{background:transparent!important}
